config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    resources :sellers do
        resources :reviews
    end
    root 'sellers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :sellers
    belongs_to :user
end

app/models/seller.rb
class Seller < ApplicationRecord
    belongs_to :user
    has_many :reviews

    has_attached_file :food_img, styles: { medium: "425x300>", thumb: "425x300>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :food_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    has_many :sellers
    has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_food

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.seller_id = @seller.id
        @review.user_id = current_user.id
        if @review.save
            redirect_to seller_path(@seller)
        else
            render 'new'
        end
    end

private
    def review_params
        params.require(:review).permit(:rating)
    end

    def find_food
        @seller = Seller.find(params[:seller_id])
    end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
    before_action :find_food, only: [:show, :edit, :update, :destroy]

    def index
        @sellers = Seller.all.order("created_at DESC")
    end

    def show
        @seller = Seller.find(params[:id])
    end

    def new
        @seller = current_user.sellers.build
    end

    def create
        @seller = current_user.sellers.build(seller_params)

        if @seller.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @seller.update(seller_params)
            redirect_to seller_path(@seller)
        else
            render 'edit'
        end
    end

    def destroy
        @seller.destroy
        redirect_to root_path
    end

private
    def seller_params
        params.require(:seller).permit(:food, :location, :price, :date, :mobile, :details, :food_img)
    end

    def find_food
        @seller = Seller.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <%= link_to "Hungry", root_path, class: "navbar-brand" %>
            </div>
            <ul class="nav navbar-nav">
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <% if user_signed_in? %>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Log in", new_user_session_path %></li>
                <% end %>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li><%= link_to "Add new food", new_seller_path %></li>
                <% end %>
            </ul>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

       <div class="container">
           <%= yield %>
       </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@seller, @seller.reviews.build]) do |f| %>
    <%= f.input :rating %>
    <%= f.button :submit %>
<% end %>

app/views/sellers/_form.html.erb
<%= simple_form_for @seller do |f| %>
    <%= f.input :food, label: "Food" %>
    <%= f.input :location, label: "Location" %>
    <%= f.input :price, label: "Price" %>
    <%= f.input :date, label: "Date" %>
    <%= f.input :mobile, label: "Phone" %>
    <%= f.input :details, label: "Details" %>
    <%= f.file_field :food_img %>
    <%= f.button :submit %>

<% end %>

app/views/sellers/edit.html.erb
<h1>Edit Seller</h1>

<%= render 'form' %>

app/views/sellers/index.html.erb
<h1>Food Information</h1>

<% if @sellers.count == 0 %>
    <h1> There are no food entries in this category</h1>
<% else %>
    <div class="row">
    <% @sellers.each do |seller| %>
        <div class="col-md-4">        
            <a href="/sellers/<%= seller.id %>">
                <%= image_tag seller.food_img.url(:thumb), class: "food" %>
            </a>
        </div>
    <% end %>
    </div>
<% end %>

app/views/sellers/main.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Hungry</title>
    <style>
        /* Add a black background color to the top navigation */
        .topnav {
            background-color: #333;
            overflow: hidden;
        }
        
        /* Style the links inside the navigation bar */
        .topnav a {
            float: right;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }
        
        /* Change the color of links on hover */
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }
        
        /* Add a color to the active/current link */
        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
        
        #big {
            background-image: url("/food.jpg");
            height: 100%;
            width: 100%;
            overflow: auto;
            position: fixed;
        }
        
        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px; 
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            width: 90%;
        }
        
        #home {
            float: left;
            font-weight: bold;
            /*font-size: 25px;*/
        }
        
        /*.body {
            margin: 0;
            overflow: auto;
        }*/
        
        /*.topnav li {
            float: right;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }
        
         Change the color of links on hover 
        .topnav li:hover {
            background-color: #ddd;
            color: black;
        }
        
        /* Add a color to the active/current link 
        .topnav li.active {
            background-color: #4CAF50;
            color: white;
        }*/*/
        
    </style>
<body>
    <div id="big" >
        
        <!--Navigation Bar-->
        <!-- <div class="topnav" id="myTopnav">
            <a href="index.erb">List</a>
            <a href="#contact">Contact</a>
            <a href="#news">News</a>
            <a id="home" href="main.erb">Hungry</a>
            <ul class="nav navbar-nav">
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <% if user_signed_in? %>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Log in", new_user_session_path %></li>
                <% end %>
            </ul>
        </div> -->
        <br><br><br>
        
        <!--Search Bar-->
        <div style="text-align: center;">
            <form action="result" method="GET">
                <input id="search_bar" type="text" name="search" placeholder="Search..">
            </form>
        </div>
        
        <!--Show the search result-->
       <!--  <div style="background-color: white;">
            <% if @posts.blank? %>
                <h4>No match result for "<%= @search %>".</h4>
            <% else %>
                <h4>Matching results: </h4>
                <br>
                <% @posts.each do |p| %>
                   <h4>Food: <%= p.food %></h4>
                   <h4>Location: <%= p.location %></h4>
                   <h4>Price: $<%= p.price %></h4>
                   <h4>Date: <%= p.date %></h4>
                   <h4>Mobile: <%= p.mobile %></h4>
                   <h4>Details: <%= p.details %></h4>
                   <!--<img src=p.picture alt="image of food">-->
                  <!--  <br>
                <% end %>
            <% end %>
        </div> --> -->
        
    </div>
    
</body>

app/views/sellers/new.html.erb
<h1>Add food information</h1>

<%= render 'form' %>

app/views/sellers/result.html.erb
<!-- result.html.erb -->

<!DOCTYPE html>
<html>
<head>
	<title>Search Result</title>
	<style type="text/css">
		#big {
            background-image: url("/food.jpg");
            height: 100%;
            width: 100%;
            overflow: auto;
            position: fixed;
        }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px; 
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            width: 90%;
        }
	</style>
</head>
<body>
    <div id="big" >
    	<br>

    	<!--Search Bar-->
    	<div style="text-align: center;">
            <form action="result" method="GET">
                <input id="search_bar" type="text" name="search" placeholder="Search..">
            </form>
        </div>

        <br>

        <!--Show the search result-->
        <div style="background-color: white;">
            <% if @posts.blank? %>
                <h4>No match result for "<%= @search %>".</h4>
            <% else %>
                <h4>Matching results for "<%= @search %>": </h4>
                <br>
                <% @posts.each do |p| %>
                   <h4>Food: <%= p.food %></h4>
                   <h4>Location: <%= p.location %></h4>
                   <h4>Price: $<%= p.price %></h4>
                   <h4>Date: <%= p.date %></h4>
                   <h4>Mobile: <%= p.mobile %></h4>
                   <h4>Details: <%= p.details %></h4>
                   <!--<img src=p.picture alt="image of food">-->
                   <br>
                <% end %>
            <% end %>
        </div>
    </div>
</body>

</html>

app/views/sellers/show.html.erb
<h1>Tell us more about your food!</h1>

<div class="row">
    
    <div class="col-md-4">

        <%= image_tag @seller.food_img.url(:medium), class: "food-show" %>

    </div>
    <div class="col-md-8">

        <h2>What kind of food?: <%= @seller.food %></h2>
        <h3>Location: <%= @seller.location %></h3>
        <h3>Price($): <%= @seller.price %></h3>
        <h3>Date/Time(MM-DD-YYYY/Time): <%= @seller.date %></h3>
        <h3>Contact Number: <%= @seller.mobile %></h3>
        <p>Food Details: <%= @seller.details %></p>

    </div>  
</div>

<% if false %>
<div class="row">
    <div class="col-md-4">
        <%= render @seller.reviews %>
        <div>
            <%= link_to "Add rating", new_seller_review_path(@seller) %>
        </div>
    </div>

</div>
<% end %>

<%= link_to "Back", root_path %>

<% if user_signed_in? %>
    <% if @seller.user_id == current_user.id %>
        <%= link_to "Edit", edit_seller_path(@seller) %>
        <%= link_to "Delete", seller_path(@seller), method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
<% end %>